/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Class to storage authentication data
 */
export class AuthStorage {
  private storage: Map<string, string>;

  constructor() {
    this.storage = new Map();
  }

  /**
   * Sets the Bearer auth method value.
   *
   * @param value The new value to set for Bearer.
   */
  setBearer(value: string): this {
    this.storage.set('Bearer', value);
    return this;
  }

  /**
   * Removes the Bearer auth method value.
   */
  removeBearer(): this {
    this.storage.delete('Bearer');
    return this;
  }

  /**
   * Gets the Bearer auth method value.
   */
  getBearer(): null | string {
    return this.storage.get('Bearer') || null;
  }
}
