/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  RegisterModel,
  UserResponse,
  LoginModel,
  Tokens,
} from './models';

/**
 * apiAuthenticationLoginUserPost - parameters interface
 */
export interface IApiAuthenticationLoginUserPostParams {
  loginModel?: LoginModel;
}

/**
 * apiAuthenticationRegisterUserPost - parameters interface
 */
export interface IApiAuthenticationRegisterUserPostParams {
  registerModel?: RegisterModel;
}

/**
 * apiAuthenticationWhoAmIGet - parameters interface
 */
export interface IApiAuthenticationWhoAmIGetParams {
}

/**
 * AuthenticationApi - API class
 */
@autoinject()
export class AuthenticationApi extends Api {

  /**
   * Creates a new AuthenticationApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * @param params.loginModel 
   */
  async apiAuthenticationLoginUserPost(params: IApiAuthenticationLoginUserPostParams): Promise<Tokens> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/api/Authentication/LoginUser`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['loginModel'] || {}))

      // Authentication 'Bearer' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * @param params.registerModel 
   */
  async apiAuthenticationRegisterUserPost(params: IApiAuthenticationRegisterUserPostParams): Promise<UserResponse> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/api/Authentication/RegisterUser`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['registerModel'] || {}))

      // Authentication 'Bearer' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   */
  async apiAuthenticationWhoAmIGet(): Promise<UserResponse> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/api/Authentication/WhoAmI`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'Bearer' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

