/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CountryResponse {
  id?: number;
  name?: string;
  code?: string;
  index?: number;
}


export interface CreatePermissionRequest {
  dateStart: string;
  dateReturn: string;
  backupUserId?: string;
  permissionTypeId?: number;
  additionalComments?: string;
}


export interface CreateTicketRequest {
  ticketTypeId: number;
  benefitId?: string;
  carrierId?: number;
  dateDeparture: string;
  originStation: number;
  destinationStation: number;
  dateDesired: string;
  additionalComments?: string;
}


export interface Credential {
  id?: string;
  username?: string;
  password?: string;
  isActive?: boolean;
  userId?: string;
  type?: string;
  user?: User;
}


export interface LoginModel {
  userName: string;
  password: string;
}


export interface OrganizationResponse {
  id?: string;
  name?: string;
  code?: string;
  organizationtypeName?: string;
}


export interface Permission {
  id?: string;
  dateStart?: string;
  dateReturn?: string;
  isAllowed?: boolean;
  userId?: string;
  permissionTypeId?: number;
  permissionType?: PermissionType;
  user?: User;
  permissionHistories?: Array<PermissionHistory>;
}


export interface PermissionHistory {
  id?: number;
  permissionId?: string;
  response?: string;
  note?: string;
  authorityId?: string;
  dateDecision?: string;
  authority?: User;
  permission?: Permission;
}


export interface PermissionResponse {
  id?: string;
  dateStart?: string;
  dateReturn?: string;
  isAllowed?: boolean;
  userFirstName?: string;
  userLastName?: string;
  permissionTypeName?: string;
}


export interface PermissionType {
  id?: number;
  name?: string;
  permissions?: Array<Permission>;
}


export interface PermissionTypeResponse {
  id?: number;
  name?: string;
}


export interface PostionResponse {
  id?: string;
  name?: string;
  comment?: string;
  dateCreated?: string;
  dateUpdated?: string;
  stationName?: string;
}


export interface RegisterModel {
  firstName: string;
  lastName: string;
  matriculeNo?: string;
  email: string;
  positionId: string;
  organizationId: string;
}


export interface Request {
  id?: string;
  documentId?: string;
  isApproved?: boolean;
  requestValidators?: Array<RequestValidator>;
}


export interface RequestValidator {
  id?: string;
  validatorId?: string;
  requestId?: string;
  granted?: boolean;
  dateAction?: string;
  comment?: string;
  request?: Request;
  validator?: User;
}


export interface StationResponse {
  id?: number;
  name?: string;
  isActive?: boolean;
  codeIata?: string;
  countryName?: string;
}


export interface TicketResponse {
  id?: string;
  comment?: string;
  dateDeparture?: string;
  dateDesired?: string;
  carrierName?: number;
  beneficiaryFirstName?: string;
  beneficiaryLastName?: string;
  destinationStationName?: string;
  originStationName?: number;
  ticketTypeName?: number;
}


export interface Tokens {
  token?: string;
  refreshToken?: string;
}


export interface User {
  id?: string;
  firstName?: string;
  lastName?: string;
  matriculeNo?: string;
  email?: string;
  scope?: string;
  credentials?: Array<Credential>;
  permissionHistories?: Array<PermissionHistory>;
  permissions?: Array<Permission>;
  requestValidators?: Array<RequestValidator>;
}


export interface UserResponse {
  id?: string;
  firstName?: string;
  lastName?: string;
  matriculeNo?: string;
  email?: string;
}


export interface ValidationHanldeRequest {
  documentId?: string;
  validatorId?: string;
  hasGivenAuthorization?: boolean;
  comment?: string;
}

