/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateTicketRequest model module.
 * @module model/CreateTicketRequest
 * @version 1.0.0
 */
class CreateTicketRequest {
    /**
     * Constructs a new <code>CreateTicketRequest</code>.
     * @alias module:model/CreateTicketRequest
     * @param ticketTypeId {Number} 
     * @param dateDeparture {Date} 
     * @param originStation {Number} 
     * @param destinationStation {Number} 
     * @param dateDesired {Date} 
     */
    constructor(ticketTypeId, dateDeparture, originStation, destinationStation, dateDesired) { 
        
        CreateTicketRequest.initialize(this, ticketTypeId, dateDeparture, originStation, destinationStation, dateDesired);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ticketTypeId, dateDeparture, originStation, destinationStation, dateDesired) { 
        obj['ticketTypeId'] = ticketTypeId;
        obj['dateDeparture'] = dateDeparture;
        obj['originStation'] = originStation;
        obj['destinationStation'] = destinationStation;
        obj['dateDesired'] = dateDesired;
    }

    /**
     * Constructs a <code>CreateTicketRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTicketRequest} obj Optional instance to populate.
     * @return {module:model/CreateTicketRequest} The populated <code>CreateTicketRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTicketRequest();

            if (data.hasOwnProperty('ticketTypeId')) {
                obj['ticketTypeId'] = ApiClient.convertToType(data['ticketTypeId'], 'Number');
            }
            if (data.hasOwnProperty('benefitId')) {
                obj['benefitId'] = ApiClient.convertToType(data['benefitId'], 'String');
            }
            if (data.hasOwnProperty('carrierId')) {
                obj['carrierId'] = ApiClient.convertToType(data['carrierId'], 'Number');
            }
            if (data.hasOwnProperty('dateDeparture')) {
                obj['dateDeparture'] = ApiClient.convertToType(data['dateDeparture'], 'Date');
            }
            if (data.hasOwnProperty('originStation')) {
                obj['originStation'] = ApiClient.convertToType(data['originStation'], 'Number');
            }
            if (data.hasOwnProperty('destinationStation')) {
                obj['destinationStation'] = ApiClient.convertToType(data['destinationStation'], 'Number');
            }
            if (data.hasOwnProperty('dateDesired')) {
                obj['dateDesired'] = ApiClient.convertToType(data['dateDesired'], 'Date');
            }
            if (data.hasOwnProperty('additionalComments')) {
                obj['additionalComments'] = ApiClient.convertToType(data['additionalComments'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} ticketTypeId
 */
CreateTicketRequest.prototype['ticketTypeId'] = undefined;

/**
 * @member {String} benefitId
 */
CreateTicketRequest.prototype['benefitId'] = undefined;

/**
 * @member {Number} carrierId
 */
CreateTicketRequest.prototype['carrierId'] = undefined;

/**
 * @member {Date} dateDeparture
 */
CreateTicketRequest.prototype['dateDeparture'] = undefined;

/**
 * @member {Number} originStation
 */
CreateTicketRequest.prototype['originStation'] = undefined;

/**
 * @member {Number} destinationStation
 */
CreateTicketRequest.prototype['destinationStation'] = undefined;

/**
 * @member {Date} dateDesired
 */
CreateTicketRequest.prototype['dateDesired'] = undefined;

/**
 * @member {String} additionalComments
 */
CreateTicketRequest.prototype['additionalComments'] = undefined;






export default CreateTicketRequest;

