/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatePermissionRequest model module.
 * @module model/CreatePermissionRequest
 * @version v1
 */
class CreatePermissionRequest {
    /**
     * Constructs a new <code>CreatePermissionRequest</code>.
     * @alias module:model/CreatePermissionRequest
     * @param dateStart {Date} 
     * @param dateReturn {Date} 
     */
    constructor(dateStart, dateReturn) { 
        
        CreatePermissionRequest.initialize(this, dateStart, dateReturn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dateStart, dateReturn) { 
        obj['dateStart'] = dateStart;
        obj['dateReturn'] = dateReturn;
    }

    /**
     * Constructs a <code>CreatePermissionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePermissionRequest} obj Optional instance to populate.
     * @return {module:model/CreatePermissionRequest} The populated <code>CreatePermissionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePermissionRequest();

            if (data.hasOwnProperty('dateStart')) {
                obj['dateStart'] = ApiClient.convertToType(data['dateStart'], 'Date');
            }
            if (data.hasOwnProperty('dateReturn')) {
                obj['dateReturn'] = ApiClient.convertToType(data['dateReturn'], 'Date');
            }
            if (data.hasOwnProperty('backupUserId')) {
                obj['backupUserId'] = ApiClient.convertToType(data['backupUserId'], 'String');
            }
            if (data.hasOwnProperty('permissionTypeId')) {
                obj['permissionTypeId'] = ApiClient.convertToType(data['permissionTypeId'], 'Number');
            }
            if (data.hasOwnProperty('additionalComments')) {
                obj['additionalComments'] = ApiClient.convertToType(data['additionalComments'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} dateStart
 */
CreatePermissionRequest.prototype['dateStart'] = undefined;

/**
 * @member {Date} dateReturn
 */
CreatePermissionRequest.prototype['dateReturn'] = undefined;

/**
 * @member {String} backupUserId
 */
CreatePermissionRequest.prototype['backupUserId'] = undefined;

/**
 * @member {Number} permissionTypeId
 */
CreatePermissionRequest.prototype['permissionTypeId'] = undefined;

/**
 * @member {String} additionalComments
 */
CreatePermissionRequest.prototype['additionalComments'] = undefined;






export default CreatePermissionRequest;

