/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The Credential model module.
 * @module model/Credential
 * @version v1
 */
class Credential {
    /**
     * Constructs a new <code>Credential</code>.
     * @alias module:model/Credential
     */
    constructor() { 
        
        Credential.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Credential</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Credential} obj Optional instance to populate.
     * @return {module:model/Credential} The populated <code>Credential</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Credential();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Credential.prototype['id'] = undefined;

/**
 * @member {String} username
 */
Credential.prototype['username'] = undefined;

/**
 * @member {String} password
 */
Credential.prototype['password'] = undefined;

/**
 * @member {Boolean} isActive
 */
Credential.prototype['isActive'] = undefined;

/**
 * @member {String} userId
 */
Credential.prototype['userId'] = undefined;

/**
 * @member {String} type
 */
Credential.prototype['type'] = undefined;

/**
 * @member {module:model/User} user
 */
Credential.prototype['user'] = undefined;






export default Credential;

