/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PermissionHistory from './PermissionHistory';
import PermissionType from './PermissionType';
import User from './User';

/**
 * The Permission model module.
 * @module model/Permission
 * @version v1
 */
class Permission {
    /**
     * Constructs a new <code>Permission</code>.
     * @alias module:model/Permission
     */
    constructor() { 
        
        Permission.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Permission</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Permission} obj Optional instance to populate.
     * @return {module:model/Permission} The populated <code>Permission</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Permission();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('dateStart')) {
                obj['dateStart'] = ApiClient.convertToType(data['dateStart'], 'Date');
            }
            if (data.hasOwnProperty('dateReturn')) {
                obj['dateReturn'] = ApiClient.convertToType(data['dateReturn'], 'Date');
            }
            if (data.hasOwnProperty('isAllowed')) {
                obj['isAllowed'] = ApiClient.convertToType(data['isAllowed'], 'Boolean');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('permissionTypeId')) {
                obj['permissionTypeId'] = ApiClient.convertToType(data['permissionTypeId'], 'Number');
            }
            if (data.hasOwnProperty('permissionType')) {
                obj['permissionType'] = PermissionType.constructFromObject(data['permissionType']);
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('permissionHistories')) {
                obj['permissionHistories'] = ApiClient.convertToType(data['permissionHistories'], [PermissionHistory]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Permission.prototype['id'] = undefined;

/**
 * @member {Date} dateStart
 */
Permission.prototype['dateStart'] = undefined;

/**
 * @member {Date} dateReturn
 */
Permission.prototype['dateReturn'] = undefined;

/**
 * @member {Boolean} isAllowed
 */
Permission.prototype['isAllowed'] = undefined;

/**
 * @member {String} userId
 */
Permission.prototype['userId'] = undefined;

/**
 * @member {Number} permissionTypeId
 */
Permission.prototype['permissionTypeId'] = undefined;

/**
 * @member {module:model/PermissionType} permissionType
 */
Permission.prototype['permissionType'] = undefined;

/**
 * @member {module:model/User} user
 */
Permission.prototype['user'] = undefined;

/**
 * @member {Array.<module:model/PermissionHistory>} permissionHistories
 */
Permission.prototype['permissionHistories'] = undefined;






export default Permission;

