/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PermissionResponse model module.
 * @module model/PermissionResponse
 * @version 1.0.0
 */
class PermissionResponse {
    /**
     * Constructs a new <code>PermissionResponse</code>.
     * @alias module:model/PermissionResponse
     */
    constructor() { 
        
        PermissionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionResponse} obj Optional instance to populate.
     * @return {module:model/PermissionResponse} The populated <code>PermissionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('dateStart')) {
                obj['dateStart'] = ApiClient.convertToType(data['dateStart'], 'Date');
            }
            if (data.hasOwnProperty('dateReturn')) {
                obj['dateReturn'] = ApiClient.convertToType(data['dateReturn'], 'Date');
            }
            if (data.hasOwnProperty('isAllowed')) {
                obj['isAllowed'] = ApiClient.convertToType(data['isAllowed'], 'Boolean');
            }
            if (data.hasOwnProperty('userFirstName')) {
                obj['userFirstName'] = ApiClient.convertToType(data['userFirstName'], 'String');
            }
            if (data.hasOwnProperty('userLastName')) {
                obj['userLastName'] = ApiClient.convertToType(data['userLastName'], 'String');
            }
            if (data.hasOwnProperty('permissionTypeName')) {
                obj['permissionTypeName'] = ApiClient.convertToType(data['permissionTypeName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PermissionResponse.prototype['id'] = undefined;

/**
 * @member {Date} dateStart
 */
PermissionResponse.prototype['dateStart'] = undefined;

/**
 * @member {Date} dateReturn
 */
PermissionResponse.prototype['dateReturn'] = undefined;

/**
 * @member {Boolean} isAllowed
 */
PermissionResponse.prototype['isAllowed'] = undefined;

/**
 * @member {String} userFirstName
 */
PermissionResponse.prototype['userFirstName'] = undefined;

/**
 * @member {String} userLastName
 */
PermissionResponse.prototype['userLastName'] = undefined;

/**
 * @member {String} permissionTypeName
 */
PermissionResponse.prototype['permissionTypeName'] = undefined;






export default PermissionResponse;

