/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Permission from './Permission';

/**
 * The PermissionType model module.
 * @module model/PermissionType
 * @version 1.0.0
 */
class PermissionType {
    /**
     * Constructs a new <code>PermissionType</code>.
     * @alias module:model/PermissionType
     */
    constructor() { 
        
        PermissionType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionType} obj Optional instance to populate.
     * @return {module:model/PermissionType} The populated <code>PermissionType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], [Permission]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
PermissionType.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PermissionType.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/Permission>} permissions
 */
PermissionType.prototype['permissions'] = undefined;






export default PermissionType;

