/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Permission from './Permission';
import User from './User';

/**
 * The PermissionHistory model module.
 * @module model/PermissionHistory
 * @version 1.0.0
 */
class PermissionHistory {
    /**
     * Constructs a new <code>PermissionHistory</code>.
     * @alias module:model/PermissionHistory
     */
    constructor() { 
        
        PermissionHistory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PermissionHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PermissionHistory} obj Optional instance to populate.
     * @return {module:model/PermissionHistory} The populated <code>PermissionHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PermissionHistory();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('permissionId')) {
                obj['permissionId'] = ApiClient.convertToType(data['permissionId'], 'String');
            }
            if (data.hasOwnProperty('response')) {
                obj['response'] = ApiClient.convertToType(data['response'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('authorityId')) {
                obj['authorityId'] = ApiClient.convertToType(data['authorityId'], 'String');
            }
            if (data.hasOwnProperty('dateDecision')) {
                obj['dateDecision'] = ApiClient.convertToType(data['dateDecision'], 'Date');
            }
            if (data.hasOwnProperty('authority')) {
                obj['authority'] = User.constructFromObject(data['authority']);
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = Permission.constructFromObject(data['permission']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
PermissionHistory.prototype['id'] = undefined;

/**
 * @member {String} permissionId
 */
PermissionHistory.prototype['permissionId'] = undefined;

/**
 * @member {String} response
 */
PermissionHistory.prototype['response'] = undefined;

/**
 * @member {String} note
 */
PermissionHistory.prototype['note'] = undefined;

/**
 * @member {String} authorityId
 */
PermissionHistory.prototype['authorityId'] = undefined;

/**
 * @member {Date} dateDecision
 */
PermissionHistory.prototype['dateDecision'] = undefined;

/**
 * @member {module:model/User} authority
 */
PermissionHistory.prototype['authority'] = undefined;

/**
 * @member {module:model/Permission} permission
 */
PermissionHistory.prototype['permission'] = undefined;






export default PermissionHistory;

