/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostionResponse model module.
 * @module model/PostionResponse
 * @version v1
 */
class PostionResponse {
    /**
     * Constructs a new <code>PostionResponse</code>.
     * @alias module:model/PostionResponse
     */
    constructor() { 
        
        PostionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostionResponse} obj Optional instance to populate.
     * @return {module:model/PostionResponse} The populated <code>PostionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostionResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('dateCreated')) {
                obj['dateCreated'] = ApiClient.convertToType(data['dateCreated'], 'Date');
            }
            if (data.hasOwnProperty('dateUpdated')) {
                obj['dateUpdated'] = ApiClient.convertToType(data['dateUpdated'], 'Date');
            }
            if (data.hasOwnProperty('stationName')) {
                obj['stationName'] = ApiClient.convertToType(data['stationName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PostionResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PostionResponse.prototype['name'] = undefined;

/**
 * @member {String} comment
 */
PostionResponse.prototype['comment'] = undefined;

/**
 * @member {Date} dateCreated
 */
PostionResponse.prototype['dateCreated'] = undefined;

/**
 * @member {Date} dateUpdated
 */
PostionResponse.prototype['dateUpdated'] = undefined;

/**
 * @member {String} stationName
 */
PostionResponse.prototype['stationName'] = undefined;






export default PostionResponse;

