/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RegisterModel model module.
 * @module model/RegisterModel
 * @version v1
 */
class RegisterModel {
    /**
     * Constructs a new <code>RegisterModel</code>.
     * @alias module:model/RegisterModel
     * @param firstName {String} 
     * @param lastName {String} 
     * @param email {String} 
     * @param positionId {String} 
     * @param organizationId {String} 
     */
    constructor(firstName, lastName, email, positionId, organizationId) { 
        
        RegisterModel.initialize(this, firstName, lastName, email, positionId, organizationId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, email, positionId, organizationId) { 
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
        obj['email'] = email;
        obj['positionId'] = positionId;
        obj['organizationId'] = organizationId;
    }

    /**
     * Constructs a <code>RegisterModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterModel} obj Optional instance to populate.
     * @return {module:model/RegisterModel} The populated <code>RegisterModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterModel();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('matriculeNo')) {
                obj['matriculeNo'] = ApiClient.convertToType(data['matriculeNo'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('positionId')) {
                obj['positionId'] = ApiClient.convertToType(data['positionId'], 'String');
            }
            if (data.hasOwnProperty('organizationId')) {
                obj['organizationId'] = ApiClient.convertToType(data['organizationId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} firstName
 */
RegisterModel.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
RegisterModel.prototype['lastName'] = undefined;

/**
 * @member {String} matriculeNo
 */
RegisterModel.prototype['matriculeNo'] = undefined;

/**
 * @member {String} email
 */
RegisterModel.prototype['email'] = undefined;

/**
 * @member {String} positionId
 */
RegisterModel.prototype['positionId'] = undefined;

/**
 * @member {String} organizationId
 */
RegisterModel.prototype['organizationId'] = undefined;






export default RegisterModel;

