/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Request from './Request';
import User from './User';

/**
 * The RequestValidator model module.
 * @module model/RequestValidator
 * @version v1
 */
class RequestValidator {
    /**
     * Constructs a new <code>RequestValidator</code>.
     * @alias module:model/RequestValidator
     */
    constructor() { 
        
        RequestValidator.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RequestValidator</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequestValidator} obj Optional instance to populate.
     * @return {module:model/RequestValidator} The populated <code>RequestValidator</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequestValidator();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('validatorId')) {
                obj['validatorId'] = ApiClient.convertToType(data['validatorId'], 'String');
            }
            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
            }
            if (data.hasOwnProperty('granted')) {
                obj['granted'] = ApiClient.convertToType(data['granted'], 'Boolean');
            }
            if (data.hasOwnProperty('dateAction')) {
                obj['dateAction'] = ApiClient.convertToType(data['dateAction'], 'Date');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = Request.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('validator')) {
                obj['validator'] = User.constructFromObject(data['validator']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
RequestValidator.prototype['id'] = undefined;

/**
 * @member {String} validatorId
 */
RequestValidator.prototype['validatorId'] = undefined;

/**
 * @member {String} requestId
 */
RequestValidator.prototype['requestId'] = undefined;

/**
 * @member {Boolean} granted
 */
RequestValidator.prototype['granted'] = undefined;

/**
 * @member {Date} dateAction
 */
RequestValidator.prototype['dateAction'] = undefined;

/**
 * @member {String} comment
 */
RequestValidator.prototype['comment'] = undefined;

/**
 * @member {module:model/Request} request
 */
RequestValidator.prototype['request'] = undefined;

/**
 * @member {module:model/User} validator
 */
RequestValidator.prototype['validator'] = undefined;






export default RequestValidator;

