/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateTicketRequest from '../model/CreateTicketRequest';
import TicketResponse from '../model/TicketResponse';

/**
* Ticket service.
* @module api/TicketApi
* @version 1.0.0
*/
export default class TicketApi {

    /**
    * Constructs a new TicketApi. 
    * @alias module:api/TicketApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiTicketCreateTicketRequestPost operation.
     * @callback module:api/TicketApi~apiTicketCreateTicketRequestPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TicketResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateTicketRequest} opts.createTicketRequest 
     * @param {module:api/TicketApi~apiTicketCreateTicketRequestPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TicketResponse}
     */
    apiTicketCreateTicketRequestPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['createTicketRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = TicketResponse;
      return this.apiClient.callApi(
        '/api/Ticket/CreateTicketRequest', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
