/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreatePermissionRequest from '../model/CreatePermissionRequest';
import Permission from '../model/Permission';
import PermissionResponse from '../model/PermissionResponse';

/**
* Vacation service.
* @module api/VacationApi
* @version v1
*/
export default class VacationApi {

    /**
    * Constructs a new VacationApi. 
    * @alias module:api/VacationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the apiVacationGetVacationRequestsGet operation.
     * @callback module:api/VacationApi~apiVacationGetVacationRequestsGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PermissionResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/VacationApi~apiVacationGetVacationRequestsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PermissionResponse>}
     */
    apiVacationGetVacationRequestsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = [PermissionResponse];
      return this.apiClient.callApi(
        '/api/Vacation/GetVacationRequests', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiVacationMakeVacationRequestPost operation.
     * @callback module:api/VacationApi~apiVacationMakeVacationRequestPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Permission} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/CreatePermissionRequest} opts.createPermissionRequest 
     * @param {module:api/VacationApi~apiVacationMakeVacationRequestPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Permission}
     */
    apiVacationMakeVacationRequestPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['createPermissionRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = Permission;
      return this.apiClient.callApi(
        '/api/Vacation/MakeVacationRequest', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
