/* tslint:disable */
/* eslint-disable */
/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ValidationHanldeRequest,
} from '../models';
import {
    ValidationHanldeRequestFromJSON,
    ValidationHanldeRequestToJSON,
} from '../models';

export interface ApiRequestHandleValidationPostRequest {
    validationHanldeRequest?: ValidationHanldeRequest;
}

/**
 * 
 */
export class RequestApi extends runtime.BaseAPI {

    /**
     */
    async apiRequestHandleValidationPostRaw(requestParameters: ApiRequestHandleValidationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Request/HandleValidation`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ValidationHanldeRequestToJSON(requestParameters.validationHanldeRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiRequestHandleValidationPost(requestParameters: ApiRequestHandleValidationPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.apiRequestHandleValidationPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
