/* tslint:disable */
/* eslint-disable */
/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTicketRequest,
  TicketResponse,
} from '../models';
import {
    CreateTicketRequestFromJSON,
    CreateTicketRequestToJSON,
    TicketResponseFromJSON,
    TicketResponseToJSON,
} from '../models';

export interface ApiTicketCreateTicketRequestPostRequest {
    createTicketRequest?: CreateTicketRequest;
}

/**
 * 
 */
export class TicketApi extends runtime.BaseAPI {

    /**
     */
    async apiTicketCreateTicketRequestPostRaw(requestParameters: ApiTicketCreateTicketRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TicketResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Ticket/CreateTicketRequest`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTicketRequestToJSON(requestParameters.createTicketRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiTicketCreateTicketRequestPost(requestParameters: ApiTicketCreateTicketRequestPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TicketResponse> {
        const response = await this.apiTicketCreateTicketRequestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
