/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HrApi);
  }
}(this, function(expect, HrApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HrApi.TicketResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TicketResponse', function() {
    it('should create an instance of TicketResponse', function() {
      // uncomment below and update the code to test TicketResponse
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be.a(HrApi.TicketResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property dateDeparture (base name: "dateDeparture")', function() {
      // uncomment below and update the code to test the property dateDeparture
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property dateDesired (base name: "dateDesired")', function() {
      // uncomment below and update the code to test the property dateDesired
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property carrierName (base name: "carrierName")', function() {
      // uncomment below and update the code to test the property carrierName
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property beneficiaryFirstName (base name: "beneficiaryFirstName")', function() {
      // uncomment below and update the code to test the property beneficiaryFirstName
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property beneficiaryLastName (base name: "beneficiaryLastName")', function() {
      // uncomment below and update the code to test the property beneficiaryLastName
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property destinationStationName (base name: "destinationStationName")', function() {
      // uncomment below and update the code to test the property destinationStationName
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property originStationName (base name: "originStationName")', function() {
      // uncomment below and update the code to test the property originStationName
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

    it('should have the property ticketTypeName (base name: "ticketTypeName")', function() {
      // uncomment below and update the code to test the property ticketTypeName
      //var instance = new HrApi.TicketResponse();
      //expect(instance).to.be();
    });

  });

}));
