/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreatePermissionRequest {
    'dateStart': Date;
    'dateReturn': Date;
    'backupUserId'?: string;
    'permissionTypeId'?: number;
    'additionalComments'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dateStart",
            "baseName": "dateStart",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateReturn",
            "baseName": "dateReturn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "backupUserId",
            "baseName": "backupUserId",
            "type": "string",
            "format": ""
        },
        {
            "name": "permissionTypeId",
            "baseName": "permissionTypeId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "additionalComments",
            "baseName": "additionalComments",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreatePermissionRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

