/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateTicketRequest {
    'ticketTypeId': number;
    'benefitId'?: string;
    'carrierId'?: number;
    'dateDeparture': Date;
    'originStation': number;
    'destinationStation': number;
    'dateDesired': Date;
    'additionalComments'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ticketTypeId",
            "baseName": "ticketTypeId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "benefitId",
            "baseName": "benefitId",
            "type": "string",
            "format": ""
        },
        {
            "name": "carrierId",
            "baseName": "carrierId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dateDeparture",
            "baseName": "dateDeparture",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "originStation",
            "baseName": "originStation",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "destinationStation",
            "baseName": "destinationStation",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dateDesired",
            "baseName": "dateDesired",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "additionalComments",
            "baseName": "additionalComments",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateTicketRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

