/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PermissionHistory } from './PermissionHistory';
import { PermissionType } from './PermissionType';
import { User } from './User';
import { HttpFile } from '../http/http';

export class Permission {
    'id'?: string;
    'dateStart'?: Date;
    'dateReturn'?: Date;
    'isAllowed'?: boolean;
    'userId'?: string;
    'permissionTypeId'?: number;
    'permissionType'?: PermissionType;
    'user'?: User;
    'permissionHistories'?: Array<PermissionHistory>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateStart",
            "baseName": "dateStart",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateReturn",
            "baseName": "dateReturn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isAllowed",
            "baseName": "isAllowed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string",
            "format": ""
        },
        {
            "name": "permissionTypeId",
            "baseName": "permissionTypeId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "permissionType",
            "baseName": "permissionType",
            "type": "PermissionType",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User",
            "format": ""
        },
        {
            "name": "permissionHistories",
            "baseName": "permissionHistories",
            "type": "Array<PermissionHistory>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Permission.attributeTypeMap;
    }

    public constructor() {
    }
}

