/* tslint:disable */
/* eslint-disable */
/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
} from './Permission';

/**
 * 
 * @export
 * @interface PermissionType
 */
export interface PermissionType {
    /**
     * 
     * @type {number}
     * @memberof PermissionType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PermissionType
     */
    name?: string | null;
    /**
     * 
     * @type {Array<Permission>}
     * @memberof PermissionType
     */
    permissions?: Array<Permission> | null;
}

/**
 * Check if a given object implements the PermissionType interface.
 */
export function instanceOfPermissionType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PermissionTypeFromJSON(json: any): PermissionType {
    return PermissionTypeFromJSONTyped(json, false);
}

export function PermissionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'permissions': !exists(json, 'permissions') ? undefined : (json['permissions'] === null ? null : (json['permissions'] as Array<any>).map(PermissionFromJSON)),
    };
}

export function PermissionTypeToJSON(value?: PermissionType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'permissions': value.permissions === undefined ? undefined : (value.permissions === null ? null : (value.permissions as Array<any>).map(PermissionToJSON)),
    };
}

