/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PermissionResponse {
    'id'?: string;
    'dateStart'?: Date;
    'dateReturn'?: Date;
    'isAllowed'?: boolean;
    'userFirstName'?: string;
    'userLastName'?: string;
    'permissionTypeName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateStart",
            "baseName": "dateStart",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateReturn",
            "baseName": "dateReturn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isAllowed",
            "baseName": "isAllowed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "userFirstName",
            "baseName": "userFirstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "userLastName",
            "baseName": "userLastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "permissionTypeName",
            "baseName": "permissionTypeName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PermissionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

