/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Permission } from './Permission';
import { User } from './User';
import { HttpFile } from '../http/http';

export class PermissionHistory {
    'id'?: number;
    'permissionId'?: string;
    'response'?: string;
    'note'?: string;
    'authorityId'?: string;
    'dateDecision'?: Date;
    'authority'?: User;
    'permission'?: Permission;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "permissionId",
            "baseName": "permissionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorityId",
            "baseName": "authorityId",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateDecision",
            "baseName": "dateDecision",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "authority",
            "baseName": "authority",
            "type": "User",
            "format": ""
        },
        {
            "name": "permission",
            "baseName": "permission",
            "type": "Permission",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PermissionHistory.attributeTypeMap;
    }

    public constructor() {
    }
}

