/* tslint:disable */
/* eslint-disable */
/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostionResponse
 */
export interface PostionResponse {
    /**
     * 
     * @type {string}
     * @memberof PostionResponse
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostionResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostionResponse
     */
    comment?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PostionResponse
     */
    dateCreated?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PostionResponse
     */
    dateUpdated?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PostionResponse
     */
    stationName?: string | null;
}

/**
 * Check if a given object implements the PostionResponse interface.
 */
export function instanceOfPostionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostionResponseFromJSON(json: any): PostionResponse {
    return PostionResponseFromJSONTyped(json, false);
}

export function PostionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'dateCreated': !exists(json, 'dateCreated') ? undefined : (new Date(json['dateCreated'])),
        'dateUpdated': !exists(json, 'dateUpdated') ? undefined : (json['dateUpdated'] === null ? null : new Date(json['dateUpdated'])),
        'stationName': !exists(json, 'stationName') ? undefined : json['stationName'],
    };
}

export function PostionResponseToJSON(value?: PostionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'comment': value.comment,
        'dateCreated': value.dateCreated === undefined ? undefined : (value.dateCreated.toISOString()),
        'dateUpdated': value.dateUpdated === undefined ? undefined : (value.dateUpdated === null ? null : value.dateUpdated.toISOString()),
        'stationName': value.stationName,
    };
}

