/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PostionResponse {
    'id'?: string;
    'name'?: string;
    'comment'?: string;
    'dateCreated'?: Date;
    'dateUpdated'?: Date;
    'stationName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateUpdated",
            "baseName": "dateUpdated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "stationName",
            "baseName": "stationName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PostionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

