/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Request } from './Request';
import { User } from './User';
import { HttpFile } from '../http/http';

export class RequestValidator {
    'id'?: string;
    'validatorId'?: string;
    'requestId'?: string;
    'granted'?: boolean;
    'dateAction'?: Date;
    'comment'?: string;
    'request'?: Request;
    'validator'?: User;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "validatorId",
            "baseName": "validatorId",
            "type": "string",
            "format": ""
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string",
            "format": ""
        },
        {
            "name": "granted",
            "baseName": "granted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dateAction",
            "baseName": "dateAction",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "request",
            "baseName": "request",
            "type": "Request",
            "format": ""
        },
        {
            "name": "validator",
            "baseName": "validator",
            "type": "User",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RequestValidator.attributeTypeMap;
    }

    public constructor() {
    }
}

