/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestValidator } from './RequestValidator';
import { HttpFile } from '../http/http';

export class Request {
    'id'?: string;
    'documentId'?: string;
    'isApproved'?: boolean;
    'requestValidators'?: Array<RequestValidator>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "isApproved",
            "baseName": "isApproved",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "requestValidators",
            "baseName": "requestValidators",
            "type": "Array<RequestValidator>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Request.attributeTypeMap;
    }

    public constructor() {
    }
}

