/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TicketResponse {
    'id'?: string;
    'comment'?: string;
    'dateDeparture'?: Date;
    'dateDesired'?: Date;
    'carrierName'?: number;
    'beneficiaryFirstName'?: string;
    'beneficiaryLastName'?: string;
    'destinationStationName'?: string;
    'originStationName'?: number;
    'ticketTypeName'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateDeparture",
            "baseName": "dateDeparture",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dateDesired",
            "baseName": "dateDesired",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "carrierName",
            "baseName": "carrierName",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "beneficiaryFirstName",
            "baseName": "beneficiaryFirstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "beneficiaryLastName",
            "baseName": "beneficiaryLastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationStationName",
            "baseName": "destinationStationName",
            "type": "string",
            "format": ""
        },
        {
            "name": "originStationName",
            "baseName": "originStationName",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ticketTypeName",
            "baseName": "ticketTypeName",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return TicketResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

