/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Credential } from './Credential';
import { Permission } from './Permission';
import { PermissionHistory } from './PermissionHistory';
import { RequestValidator } from './RequestValidator';
import { HttpFile } from '../http/http';

export class User {
    'id'?: string;
    'firstName'?: string;
    'lastName'?: string;
    'matriculeNo'?: string;
    'email'?: string;
    'scope'?: string;
    'credentials'?: Array<Credential>;
    'permissionHistories'?: Array<PermissionHistory>;
    'permissions'?: Array<Permission>;
    'requestValidators'?: Array<RequestValidator>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "matriculeNo",
            "baseName": "matriculeNo",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "Array<Credential>",
            "format": ""
        },
        {
            "name": "permissionHistories",
            "baseName": "permissionHistories",
            "type": "Array<PermissionHistory>",
            "format": ""
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<Permission>",
            "format": ""
        },
        {
            "name": "requestValidators",
            "baseName": "requestValidators",
            "type": "Array<RequestValidator>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}

