/* tslint:disable */
/* eslint-disable */
/**
 * HR API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationHanldeRequest
 */
export interface ValidationHanldeRequest {
    /**
     * 
     * @type {string}
     * @memberof ValidationHanldeRequest
     */
    documentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ValidationHanldeRequest
     */
    validatorId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ValidationHanldeRequest
     */
    hasGivenAuthorization?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ValidationHanldeRequest
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the ValidationHanldeRequest interface.
 */
export function instanceOfValidationHanldeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ValidationHanldeRequestFromJSON(json: any): ValidationHanldeRequest {
    return ValidationHanldeRequestFromJSONTyped(json, false);
}

export function ValidationHanldeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationHanldeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': !exists(json, 'documentId') ? undefined : json['documentId'],
        'validatorId': !exists(json, 'validatorId') ? undefined : json['validatorId'],
        'hasGivenAuthorization': !exists(json, 'hasGivenAuthorization') ? undefined : json['hasGivenAuthorization'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function ValidationHanldeRequestToJSON(value?: ValidationHanldeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'documentId': value.documentId,
        'validatorId': value.validatorId,
        'hasGivenAuthorization': value.hasGivenAuthorization,
        'comment': value.comment,
    };
}

